### ISSUE TITLE
Rename the "Tools" directory to ".tools"

### ISSUE THREAD

**Issue by jhendrixMSFT** [dotnet/buildtools#1046]
By convention our infrastructure directories should be a "dot directory", so we should rename the "Tools" directory to ".tools".

**Comment by mellinoe** [comment]
Like I said in the other PR, I don't like this convention; I don't think we should have any of our folders be hidden unless there's a really good reason to do so. Additionally, running tools from this directory is very common. I understand there's a desire to hide all that away in the run tool, but I'm doubtful we will ever get to a point where folks are not still directly running some commands from this directory.

Even from a practical perspective I don't really see the value. It's going to cause a lot of confusion, IMO. What are the upsides?

**Comment by AtsushiKan** [comment]
If the purpose is to avoid collisions, why not set aside <b>one</b> reserved directory name and everything (Tools, packages, bin) placed under it. 

And if it has to start with a ".", I'd prefer that second letter be something that sorts before "g".

Because sooner or later, I'm going to by "rd /S /Q .tools" routine, hit TAB for auto-completion one keystroke too early and yay! no more ".git" directory.

**Comment by bryanar** [comment]
@mellinoe I am skeptical that a change like this is going to cause _a lot_ of confusion, any idea if people are frequently not showing hidden files by default? Would documenting, or adding it to our output be helpful in anyway to avoid the confusion? I am in favor of the change if we can prevent confusion from cropping up in another way. 

@AtsushiKan 

Here are some names that fit your constraints (which I think are reasonable :P):

```
.cache
.buildcache
.fetch
.framework
.buildtools
.build_tools
.buildtooling
.build_tooling
.get
.build_framework
.buildfx
.buildframework
.common
.common_tooling

```

Probably more (anyone a Boggle/Wordament champion?)

IMO, if we want people to adopt using the build tooling we should strive as much as possible to get out of their way, I see this as a move in that direction. I am not super savvy on whether we should build in to this directory, or if we should build in to the repositories' bin directory? I do like the idea of keeping all of OUR eggs in this basket, while the repository owners can rely on their on bin directory to contain solely their outputs.

**Comment by AtsushiKan** [comment]
The bin directory should be kept separate. Doing a clean-build (for people like me who don’t trust incremental build and never will) and doing a clean-sync are two separate decisions.

This list of directories is considerably longer than I anticipated. I’d really prefer to see them collected under an umbrella directory if they’re going to be that many.

**Comment by bryanar** [comment]
@AtsushiKan 
I like your bin idea. 

That list was just a POSSIBLE list of names for you to pick from. I.e. you said "I want .tools, but I want the name changed." Hence I produced a list of names for you to pick from :)

**Comment by AtsushiKan** [comment]
>That list was just a POSSIBLE list of names for you to pick from.

Ok, cool. Just as long the number of non-repo directories remain manageable.

**Comment by mellinoe** [comment]
> @mellinoe I am skeptical that a change like this is going to cause a lot of confusion, any idea if people are frequently not showing hidden files by default? Would documenting, or adding it to our output be helpful in anyway to avoid the confusion? I am in favor of the change if we can prevent confusion from cropping up in another way.

`ls` doesn't show dot-named files/folders by default, unless you pass `-a`. This will be confusing for people building outside of Windows, and will be less discoverable. These aren't "hidden folders" in the Windows sense; Windows still shows them there and they are still visible in all places that I can tell, unless you are doing something special to filter them.

Anyways, what's the benefit of doing this? Are we trying to express some sentiment that these folders are "not part of the repo"? Because we already have lots of dot-named files which ARE part of various repos, and I'm not even including .git, .gitignore, .gitattributes, etc. which are also part of the repo.

**Comment by bryanar** [comment]
> ls doesn't show dot-named files/folders by default, unless you pass -a. This will be confusing for people building outside of Windows, and will be less discoverable

GOOD! This is exactly the point. It's a **bad _user experience_** to have to require deconstructing our build tools to accomplish a task. What would be really productive here is if we could understand why people feel the need to go execute things directly from within build tools, and then extract that in to the repository. 

> Anyways, what's the benefit of doing this?

I'll answer this socratically: What's the point of private/protected variables/methods on a class?

**Comment by mellinoe** [comment]
My original point was that we don't (yet) have the proper encapsulation to just replace everything with the run tool, if that is what you're implying. I'm just basing my answers on my own workflow in our repos, which involves invoking some things directly from the tools directory. I accept that I might be an oddball if some other folks want to chime in, or if we want to say we're going all-in with discouraging people from running tools directly. If the run tool was an easy replacement for everything I do, then I could see the benefit. That may already be the case, and I just need to adapt my workflow.

**Comment by dagood** [comment]
I tend to do manual runs of dependency auto-update targets using `Tools\msbuild.(cmd|sh) ...` because it's repo-independent. I don't want to add these things to the `config.json`s because there isn't a way to "inherit" generic commands from buildtools (yet) and I don't want to maintain the config in each repo.

That said, I'm fine typing `.tools` instead, trading a capital letter for a `.`. I think it's fine for people to need docs or guidance, or see stuff in logs before knowing that `.tools` exists. A `git clean -xdf` will get rid of it anyway, and `git clean -xdn` is a discovery path.

To refresh `Tools` on Windows I use `init-tools -force`, and on *nix, tab completion works differently, so I don't have the alphabetical problem. Of those options, though, I like `.buildtools`, but to make it more inclusive (we stick CLI in there too) maybe `.dotnettools`, `.dotnet-tools`, `.dotnet-build`. ("Build tools" doesn't necessarily mean the buildtools repo, but I think I'd make that assumption if I saw the names.)

**Comment by markwilkie** [comment]
@mellinoe (and others), could you file issues for all the scenarios/tasks which require direct invocation inside of build tools please?  I agree that we're not there yet w/ encapsulation, but it sure would be great to get there for at least the vast majority of the dev workflow scenarios.

**Comment by weshaggard** [comment]
>Because sooner or later, I'm going to by "rd /S /Q .tools" routine, hit TAB for auto-completion one keystroke too early and yay! no more ".git" directory.

@AtsushiKan I would highly recommend using clean.cmd/sh or at a minimum git clean over doing that. 

As for the naming I'm not hung up on using `.` as a prefix but I do think it better conveys the message that this is special and not part of the repo itself, if it weren't for the stronger desire keep a repo self-contained under one directory I would suggest we move it to another directory outside of the source tree as well.  At any rate I leave the naming decision up to the engineering team to gather some consensus.

**Comment by dleeapho** [comment]
Lots of good discussion but Tools seems like a defacto convention.
