### ISSUE TITLE
Tests don't publish updated libraries for incremental builds

### ISSUE THREAD

**Issue by weshaggard** [dotnet/buildtools#1098]
See comments at https://github.com/dotnet/buildtools/pull/1095

The basic issue is our runner scripts and our VS copy steps don't take into account when we are building live dependencies incrementally as it will not copy them to the test output directory.

**Comment by weshaggard** [comment]
cc @ericstj @MattGal

**Comment by weshaggard** [comment]
For reference there are a few requirements we need to try and maintain.

1. The running, including the copying, works consistently between local, CI, and official test runs.
2. Dev's can perform an incremental build which will update test output directory with any files that have changed.
3. Dev's can F5 and test the default configuration in VS. Ideally we would provide a way to F5 other TestTFM's but there doesn't seem to be an obvious solution for that right now.

In the end we need to make sure we aren't duplicating the list of files that are needed for running or the xunit command line construction. As those are too easy to get out of sync and will just cause problems with various systems doing slightly different things.

**Comment by ericstj** [comment]
I see two problems here:  
1. Copy is skipping if the file exists.
2. Copy is getting paths that overlap with files provided by the project.

1 is easy to fix, just overwrite, potentially skipping if the files are the same.
2 is happening because the list isn't being filtered.  I believe that _TestCopyLocalByFileNameWithoutDuplicates should exclude any items that have the same filename as the SourcesToCopyToTestDir.  This used to just happen correctly when TestCopyLocal meant the set of items to copy local, from both packages and build.  But I believe the test script work made TestCopyLocal to mean only the things that came from packages, then removed the build outputs including the deduping that happened when including them.

**Comment by MattGal** [comment]
I'm experimentally verifying whether #2 even remains a problem at the moment.   I believe we do already have items representing both filtered and un-filtered lists here, it may just be a matter of doing the plumbing to get them there.  

#1 is simple for the files copied by the MSBuild copy task but slightly trickier for the files coming from the package cache copied by the RunTests script.  Do you favor changing the script to always overwrite, or to make this optional behavior?

**Comment by weshaggard** [comment]
>Do you favor changing the script to always overwrite, or to make this optional behavior?

We should do some validation on this to see what it does for our incremental builds. I suspect it will cause things to copy every time and if that is the case then I don't like that solution.
