### ISSUE TITLE
Xunit.runner.uwp fails to build

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#1132]
On a fresh machine I cannot build buildtools due to this project's dependencies.

```
C:\src\buildtools\src\xunit.runner.uwp\xunit.runner.uwp.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'Windows.Foundation.UniversalApiContract.winmd'
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.2\Microsoft.Windows.UI.Xaml.Common.targets(264,5): Xaml Internal Error error WMC9999: Type universe cannot resolve assembly: Windows.Foundation.UniversalApiContract, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime. [C:\src\buildtools\src\xunit.runner.uwp\xunit.runner.uwp.csproj]
```

We should be able to build clean with out VS/UWP toolchains.  Elsewhere we've tried to flatten these dependencies.

/cc @weshaggard @crummel @MattGal

**Comment by MattGal** [comment]
@ericstj  While I agree with the sentiment, you should be aware that having recently done fresh setup on Windows 10 @ home, I'm pretty sure that VS 2015 is mandatory to build CoreFX  too at least as of last week.  

It's tricky, I'm not sure there's any sort of out-of-band UWP SDK that one can use.

**Comment by ericstj** [comment]
We packaged up windows.winmd to make this work in corefx.  We definitely don't require VS for corefx builds: it builds on mac/unix.

**Comment by crummel** [comment]
@ericstj  Looks like https://github.com/dotnet/corefx/pull/5090 is that change?  I can look at doing that here as well.

**Comment by MattGal** [comment]
@ericstj should we then change this page's 4th line? https://raw.githubusercontent.com/dotnet/corefx/master/Documentation/building/windows-instructions.md  .

**Comment by mellinoe** [comment]
Actually, we do require VS 2015 for corefx builds, unless something has changed. It had something to do with the fact that we use full MSBuild and need some nuget targets that were installed with VS. It's possible that there's some smaller thing you could point to instead of VS 2015, but I'm not sure. It's also possible that this requirement has changed sometime since I last checked. We added that line to the documentation because it was definitely necessary at the time.

**Comment by crummel** [comment]
@ericstj 
I removed the winmd requirement (https://github.com/crummel/dotnet_buildtools/commit/b84ad75f7671cedf25ba50d20b37c98a357e3982) but buildtools still seems to require VS to build.  I first got a bootstrapper error:
C:\temp\dotnet_buildtools\Tools\dotnetcli\dotnet.exe compile-csc @C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\obj\Debug\net45\dotnet-compile.rsp returned Exit Code 1
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\obj\Debug\net45\dotnet-compile.assemblyinfo.cs(2,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\obj\Debug\net45\dotnet-compile.assemblyinfo.cs(3,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\obj\Debug\net45\dotnet-compile.assemblyinfo.cs(4,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\obj\Debug\net45\dotnet-compile.assemblyinfo.cs(5,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\obj\Debug\net45\dotnet-compile.assemblyinfo.cs(2,58): error CS0518: Predefined type 'System.String' is not defined or imported
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\obj\Debug\net45\dotnet-compile.assemblyinfo.cs(3,54): error CS0518: Predefined type 'System.String' is not defined or imported
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\obj\Debug\net45\dotnet-compile.assemblyinfo.cs(4,67): error CS0518: Predefined type 'System.String' is not defined or imported
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\obj\Debug\net45\dotnet-compile.assemblyinfo.cs(5,62): error CS0518: Predefined type 'System.String' is not defined or imported
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\Program.cs(6,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\Program.cs(10,18): error CS0518: Predefined type 'System.Object' is not defined or imported
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\Program.cs(12,32): error CS0518: Predefined type 'System.String' is not defined or imported
C:\temp\dotnet_buildtools\packages\Microsoft.DotNet.BuildTools\1.0.26-prerelease-00802-01\lib\tool-runtime\Program.cs(12,23): error CS0518: Predefined type 'System.Int32' is not defined or imported

Then since that Program.cs is a dummy app I tried without it and got:
Running: C:\temp\dotnet_buildtools\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net45\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  /flp:v=normal
'msbuild.exe' is not recognized as an internal or external command,
operable program or batch file.

Build.cmd also checks for VS and exits with "Error: Visual Studio 2015 required" if it's not installed.  If we still want to do the winmd change I can but I don't think it removes the dependency on VS.

**Comment by MattGal** [comment]
@ericstj , @crummel : Perhaps the shorter term solution here would be to simply change things up to not build the UWP runner at all when the OS is not Windows_NT.  Any tests that use this 1) can only run on Windows and 2) Would be restoring a specific version of the UWP runner from a nuget feed anyways... it takes a fair amount of extra effort to even run the version that just got built.

**Comment by ericstj** [comment]
It seems reasonable to not build parts of the repo if we don't have toolsets to build them.

We should make sure that all our dependencies are deliberate.  I know for the rest of buildtools there shouldn't be any deliberate dependencies.  I'd also assert that any corefx dependencies are not deliberate.

>full MSBuild and need some nuget targets that were installed with VS

We don't require them, the problem was that they hook MSBuild centrally and if an old version was present we were getting warnings.  So the requirement wasn't "must have" it was "if have, update to at least X"

**Comment by danmosemsft** [comment]
My OS is Windows 10 and I have VS2015 and got this error. Perhaps I wasn't in the right command prompt.

**Comment by MattGal** [comment]
@danmosemsft  do you have the UWP development stuff turned on in your VS install?

**Comment by danmosemsft** [comment]
Good point ... no I don't.

Do we want to require UWP dev tools to build buildtools? We don't require them to build corefx/coreclr.

**Comment by MattGal** [comment]
I think my original suggestion (perhaps including a warning if we choose not to build the project) would make sense, anyone who isn't rebuilding it can just use the version from the NuGet feed and anyone who is can install the UWP SDK.
