### ISSUE TITLE
ResolveNuGetPackages causes unbounded growth of NuGet cache

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/buildtools#117]
While working on #116, I kept running out of disk space: I would free some up, but then just a few minutes later the drive would be full again. I discovered that a full build of CoreFX is adding over half a gig to the NuGet cache (%TEMP%\nuget), even with no changes and nothing new to download. I narrowed this down to the ResolveNuGetPackages task: something about this task is causing new packages to appear in the cache, even when they should already be there.

**Comment by akoeplinger** [comment]
I see the same behavior! Now I know why my VM is running out of disk space :smile: 

I debugged into the task and found out that in [ResolveNuGetPackages.cs#L221](https://github.com/dotnet/buildtools/blob/b748889166987caf6631383e5f3e13e59ae71980/src/Microsoft.DotNet.Build.Tasks/ResolveNuGetPackages.cs#L221) a new temp folder is generated with the package contents each time this line is executed. I suppose it tries to read the manifest and somehow inadvertently extracts the package file to disk instead of reading it in memory.

The `ManifestDeclaration` class is in the NuGet.NuManifest package, which shows @terrajobst as the author, but I can't find the source code online anywhere.

/cc @terrajobst @weshaggard please take a look

**Comment by eatdrinksleepcode** [comment]
FYI I have a fix for this that I will be posting shortly.

**Comment by weshaggard** [comment]
It looks like the temp caching is happening in https://github.com/Haacked/NuGet/blob/9f25709fafb0d8e8fc2a3b34c1b77a1cb4b8a539/src/Core/Packages/OptimizedZipPackage.cs. So it would appear that @eatdrinksleepcode fix should work nicely for this issue.
