### ISSUE TITLE
Test path doesn't include build configuration

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/buildtools#1587]
After running S.R.E.Tests for netcoreapp, I tried to run them for ILC. Unfortunately they share a single 'netstandard' output folder which will contain the wrong corelib:

`System.Private.CoreLib : Gatekeeper error GK0028 : GK0028 Assembly 'System.Private.CoreLib' is a mixed mode assembly containing managed and native code.  Only pure managed assemblies are compatible with .NET Native.`

To fix this I had to delete c:\git\corefx\bin\Windows_NT.AnyCPU.Debug\System.Runtime.Extensions.Tests\netstandard\ and rebuild the test folder. 

The problem here is that the test path doesn't include the build configuration, it only has the target group used to build and this could be the same for more than one vertical. 

@joperezr

**Comment by joperezr** [comment]
cc: @weshaggard 

Now that we are actually messing with the contents in the test folder (in uap and uapaot we call mklink for several things) and also since the actual RunTests.cmd produced there is different across different verticals, we should add build configuration to the testpath, such that we still support building and running tests across different verticals on the same enlistment without the need to be cleaning out folders.

**Comment by weshaggard** [comment]
We should have two outputs here one is the build output which is `c:\git\corefx\bin\Windows_NT.AnyCPU.Debug\System.Runtime.Extensions.Tests\netstandard\` and the other is where we execute the tests from which should be based on the configuration we are running the tests from. We used to have that split but we may have lost it with the engineering work but that is what we should do to segregate these assets.

**Comment by joperezr** [comment]
that sounds fair, and yes, we did lose that when we moved to dev/eng work.

**Comment by safern** [comment]
Buildtools changes handled in: https://github.com/dotnet/buildtools/pull/1652

CoreFX changes handled in: https://github.com/dotnet/corefx/pull/23633
