### ISSUE TITLE
1.0.0: Port auto-update "update existing PR" feature to servicing branch

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1589]
See https://github.com/dotnet/buildtools/issues/1588

**Comment by weshaggard** [comment]
@maririos why was this closed? This is still an issue which wastes folks time on a daily basis.

**Comment by dagood** [comment]
It was a triage decision. There's a significant amount of code to port over, since this functionality was added to VersionTools: CoreFX/CoreCLR 1.0.0 currently use the in-repo powershell upgrader/submitter, and Core-Setup 1.0.0 has its own project. I don't think we had a read of how much pain this is causing.

/cc @dleeapho

**Comment by weshaggard** [comment]
Usually someone like myself will have to go through a ton of PR's and merge/close them in the repo's. It isn't a ton of work but it is a manual step that has to be done daily otherwise the number of PR's grow a lot. 

Another potential option is the "auto-merge" feature when CI is green which would help a lot with this type of problem.

**Comment by maririos** [comment]
Thanks for the information @weshaggard . We'll reopen the issue so we can discuss the new input information during our triage next week

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
