### ISSUE TITLE
UpdateBuildInfoAsync adds partial version to Latest.txt

### ISSUE THREAD

**Issue by jaredpar** [dotnet/buildtools#1609]
Playing around with UpdateBuildInfoAsync today I noticed that it's not writing the value I expect to Latest.txt. I would have expected the full version number 2.6.0-dev-56735-00, but instead it's only writing the partial version dev-56735-00.

https://github.com/jaredpar/versions/commit/a37a6827c87e8ad1178075ea058aa617e2080a1a

Why is this? Having full versions here seems to be important to make it possible to use dotnet/versions as the single source of infomation about getting package information.

**Comment by jaredpar** [comment]
CC @dagood, @weshaggard

**Comment by weshaggard** [comment]
Latest.txt is just the build number part as a repo, well most repos, has many major versions so there isn't just one to put there. The full versions of each asset is in the list.

**Comment by jaredpar** [comment]
But how can this file be used in a meaningful fashion by a consumer?

**Comment by weshaggard** [comment]
It really probably be called "BuildNumber" or something along those lines now as it is closer what it is. We used to use it before we had the full package list I don't even know if we use it for much any more. 

Here is what corefx does with it, https://github.com/dotnet/corefx/blob/master/dependencies.props#L25. https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=CoreFxExpectedPrerelease&type=. We should probably stop using it and move to specific package versions everywhere, we just haven't done the clean-up.

**Comment by jaredpar** [comment]
> It really probably be called "BuildNumber"

It's using the full pre-release tag though hence not a good build number.

**Comment by weshaggard** [comment]
Yes I guess it is only useful if you want to know the full package pre-release label :(

**Comment by dagood** [comment]
Packages from a single CoreFX build have different major/minor/patch versions but the same prerelease identifier, so it's impossible to put a single full version in Latest.txt in the general case. The full prerelease rather than just build number was useful for auto-update at the time.

Now full versions (and their IDs) are available in Latest_Packages.txt (also Last_Build_Packages.txt), and when doing new dependency work we always use Latest_Packages.txt.

There's a lot more info that we'd also like to have in dotnet/versions (non-package outputs, locations to get outputs, commit hashes, dependencies at the time of that build...) but we haven't been able to work on it yet.

**Comment by jaredpar** [comment]
> Packages from a single CoreFX build have different major/minor/patch versions but the same prerelease identifier, so it's impossible to put a single full version in Latest.txt in the general case.

If that's the case I'd choose a diff name for hte file ta make it more descriptive. 

Or even possible just have a single JSON file which has all of the data as properties

**Comment by jaredpar** [comment]
Hmm, I'm liking the JSON file idea a bit. Imagine Info.json.

``` json
{ 
  "prerelease-version": "26612.00-beta",
  "sha": "...", 
  "packageList": [ "..." ] 
}
```

The nice part about JSON is that it's easy to add more data later without forcing bigger changes on the consumer. All the data is in one place.

**Comment by dagood** [comment]
Agreed, JSON's always been what we had in mind for the improvement, when we can do it. (Check out https://github.com/dotnet/buildtools/issues/986, although it's not perfect because it's based on a somewhat dead spec.)

Renaming Latest.txt sounds reasonable, but there's a decent ripple effect that makes it more costly to do that than it's probably worth. Might be good enough to list out common build-info files in a readme.md in https://github.com/dotnet/versions/tree/master/build-info/dotnet.

The question seems answered so I'm closing, but let me know if I misunderstood the issue.
