### ISSUE TITLE
Microsoft.xunit.netcore.extensions references a bunch of non-existent nuget package versions

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#1655]
These versions never shipped. https://github.com/dotnet/buildtools/blob/16ea4a8909bfb0761d5af85da44553fca92f7aef/src/nuget/Microsoft.xunit.netcore.extensions.nuspec#L34-L35

The versions shipped in 1.0 for both of these were 4.1.0.

**Comment by eerhardt** [comment]
Similarly, the dependency for `Microsoft.DotNet.BuildTools.TestSuite` is broken:

https://github.com/dotnet/buildtools/blob/2f0dec8eba53942a758910ea7b4cc79e4a7d2c36/src/nuget/Microsoft.xunit.netcore.extensions.nuspec#L31

That version never exists, so just referencing `Microsoft.xunit.netcore.extensions` alone produces:

```
error NU1603: Microsoft.xunit.netcore.extensions 2.1.0-preview3-02616-02 depends on Microsoft.DotNet.BuildTools.TestSuite (>= 1.0.0-prerelease) but Microsoft.DotNet.BuildTools.TestSuite 1.0.0-prerelease was not found. An approximate best match of Microsoft.DotNet.BuildTools.TestSuite 1.0.0-prerelease-00508-01 was resolved. 
```

Which you can see is an error.

I just wasted a decent amount of time tracking this down trying to reference this package.  Can this be fixed in buildtools?  It has been open for over 6 months.

/cc @weshaggard @dagood @joperezr

**Comment by joperezr** [comment]
Yes I believe fixing this shouldn't be that much of a problem. I could probably have some time to take care of it this week.

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
