### ISSUE TITLE
Allow dependency update pull requests to create a new commit each time

### ISSUE THREAD

**Issue by mconnew** [dotnet/buildtools#1727]
Sometimes updating dependencies will cause the WCF tests to fail due to an issue in a dependency. The automated tool to create a PR when dependencies build a new version replaces the commit if there's an existing pending update PR. This can make it hard to diagnose as the PR gets updated frequently and we lose the commit as it gets replaced. As the GitHub UI now allows to squash and rebase a PR, having a new commit for each update wouldn't cause lots of unnecessary commits in the log.  
It would also be useful to add a comment listing the CI build checks which had failed along with the link provided against the check to the failure details so that we don't lose that information when a new PR is submitted.

**Comment by dagood** [comment]
This is the same as https://github.com/dotnet/buildtools/issues/1658 (see there for the reasons it does fresh commits + force pushes now). /cc @danmosemsft @StephenBonikowsky 

A way to keep history I thought up more recently than that other issue is: after making the update changes on the target branch, do a `git reset --soft` onto the common PR branch and *then* commit. This makes sure the update is fresh (previous update commit attempts on the branch can't ruin subsequent update attempts) but also keeps commit history. I don't think this would be difficult to add.

**Comment by dagood** [comment]
I realized a problem with keeping the old commits using `git reset --soft`: when the target branch (say, `master`) gets new changes, the next update to run includes those changes in its commit. Just like trying to merge changes from `master` into a PR branch, the changes show up in GitHub and make the PR basically unreviewable.

To make this slightly better, I could separate each PR update into two commits: first, bring the PR branch up to date with `master`. Then, apply the new update changes. The PR's "files changes" still shows all the updates in `master` since the PR was created, but you can filter down to only see changes from the latest commit for reviewing.

Either way, you'd have to trust that the updater did the right thing when bringing the changes from `master`... if some unwanted change got in, the only way to reasonably detect it would be to examine the commit *after* using GitHub's "squash merge" feature, and at that point, if it's really bad, it's too late.

## Alternative 1:

> [dagood] This makes sure the update is fresh (previous update commit attempts on the branch can't ruin subsequent update attempts)

If we drop that goal, and instead accumulate updates over time on top of each other, changes from `master` would never appear in the PR. If something goes bad (merge conflict, update changes something unexpected) the PR would need to be closed--then the next update would be fresh from `master`.

This is the kind of implementation I was thinking about on the other issue. (I didn't fully understand the freshness issue at that point, though.)

## Alternative 2:

We could stop trying to keep commits and instead go all the way with:

> [mconnew] It would also be useful to add a comment listing the CI build checks which had failed along with the link provided against the check to the failure details so that we don't lose that information when a new PR is submitted.

When the auto-updater force-pushes a new update commit, it could use GitHub APIs to iterate through the PR statuses, save the links into the PR description, and push a tag for the old update commit so GitHub can't garbage collect it.

/cc @weshaggard

**Comment by mconnew** [comment]
I like alternative 2 but with a small change. You don't need a tag, just make the comment against the commit as a review comment. You would see that a comment was made against an outdated diff and you could easily view that diff.

**Comment by dagood** [comment]
Adding a PR review to "pin" the commit kind of works, but requires some extra steps to see the commit's diff. Here's my experience:

 1. Create a PR, submit a "comment" review.
 2. Force push a new commit.
 3. See the review still in PR history.
 4. Clicking the "View changes" button brings me to the "Files changed" PR page with the message "We went looking everywhere, but couldn’t find those commits.".
 5. But GitHub didn't seem to do a great job looking "everywhere"... I can extract the commit hash from the URL and craft a URL to see the commit on my GitHub fork directly.

To skip manually crafting the URL, we can post the link as the review comment body. However, people could then accidentally use the "View changes" button and think something's bugged. I think it's better off as a standalone comment (or a description edit, for anyone worried about comment/notification spam).

This does rely on GitHub not garbage collecting the commits. I wasn't able to find a definitive answer about when GitHub actually collects, though--I see answers varying from "every repo operation" to "about one month" to "GitHub won't GC unless you specifically ask support to do it". Anyway, the information is only useful for a little while, so that's probably fine. If it starts to be a problem, we can implement tagging (note: tags would be on the bot's repo fork).

(I also tried a "commit comment" rather than on a line in the PR. Those show up as comments in the PR history, but once the commit gets force pushed away, the comment disappears entirely. Presumably the comment would also disappear if the commit is GC'd, but I wasn't able to find info.)

**Comment by weshaggard** [comment]
Do we have any idea of how long it takes to GC the commits? If it is a day or so perhaps just adding a comment with the results and linking the the commit in the PR comments is good enough.

**Comment by dagood** [comment]
I can't find any official word from GitHub, just what I mentioned in "This does rely on GitHub not garbage collecting the commits. [...]" I agree it makes sense to add the comments (or description edits), then manually prevent GC by tagging if it turns out we have to. This approach is nice because it's purely incremental improvements, no paradigm shifts like Alternative 1.

**Comment by mconnew** [comment]
If the tag is only on the bot repo fork, then I don't see an issue with tagging. Could we use the tag comment to store the CI results or would that be too clunky in the UI to navigate?

**Comment by dagood** [comment]
It looks like GitHub doesn't render tag messages as Markdown (makes sense: some inputs might be misrepresented) so that wouldn't be great to navigate. I think we should stick with just using them to "pin" the commits, and only if it turns out to be needed.

I realized, though, that the commit itself shows CI status items in the `commits` view (the green check). So we can get pretty minimal (and quick to implement) by just having a list like this in the PR description:

> Discarded auto-update commits:
>  * [`48f5bd0`](https://github.com/dotnet/corefx/commits/48f5bd0efba6d5478900bbb5be63c2706e901b1c) "Update CoreFx, Standard to preview1-25820-02, preview1-25820-01, respectively"
>  * [`ff61213`](https://github.com/dotnet/corefx/commits/ff61213dc0171796d1e848b156cb07fbe8838a54) "Update BuildTools, CoreClr, ProjectNTfs, ProjectNTfsTestILC to prerelease-02120-03, preview1-25820-01, beta-25820-00, beta-25820-00, respectively"
>  * [`936049c`](https://github.com/dotnet/corefx/commits/936049c915e73bee2c3c09209df59ddf465d1e14) "Update CoreFx to preview1-25819-01"

To make sure the length of that isn't a problem:

> <details><summary>(3) Discarded auto-update commits (click me)</summary>
> 
>  * [`48f5bd0`](https://github.com/dotnet/corefx/commits/48f5bd0efba6d5478900bbb5be63c2706e901b1c) "Update CoreFx, Standard to preview1-25820-02, preview1-25820-01, respectively"
>  * [`ff61213`](https://github.com/dotnet/corefx/commits/ff61213dc0171796d1e848b156cb07fbe8838a54) "Update BuildTools, CoreClr, ProjectNTfs, ProjectNTfsTestILC to prerelease-02120-03, preview1-25820-01, beta-25820-00, beta-25820-00, respectively"
>  * [`936049c`](https://github.com/dotnet/corefx/commits/936049c915e73bee2c3c09209df59ddf465d1e14) "Update CoreFx to preview1-25819-01"
> 
> </details>

As an incremental improvement, we could also add a summary of CI status at the time each commit was discarded so you don't always have to click through. (We don't currently have an implementation of that API in `GitHubClient` to use in VersionTools--not a whole lot more work, but some.)

**Comment by mconnew** [comment]
The green tick isn't enough. We need to see what failed if it did fail. Sometimes there are problems with the CI machines of a particular platform so we need to see the individual results with links to the CI run details.

**Comment by dagood** [comment]
Did you try clicking on the green tick? It should give you a popup with all the statuses that were added to that commit. Here's an example (with failures this time): https://github.com/dotnet/corefx/commits/09f97598641d40841a541880ef212c2f3b94d4c9

**Comment by dagood** [comment]
Discarded commit tracking and CI status saving is now live. Example: https://github.com/dotnet/core-setup/pull/3372. Closing as resolved for now, but let me know if that design doesn't quite work for you.

I didn't think to handle there being no details link in the CI status, so right now there are some `[Details]()` links for triggered items that shouldn't exist. Filed https://github.com/dotnet/buildtools/issues/1773 to track fixing.
