### ISSUE TITLE
Investigate Portable PDB to Windows PDB conversion AVs

### ISSUE THREAD

**Issue by dagood** [dotnet/buildtools#1737]
The Portable PDB to Windows PDB conversion task sometimes hit AVs, so I implemented a retry workaround in https://github.com/dotnet/buildtools/pull/1623. Errors look like:

```
Converting portable PDB '[...]System.Private.Xml.dll'...
##[error]Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.DiaSymReader.ISymUnmanagedWriter5.Close()
   at Microsoft.DiaSymReader.SymUnmanagedWriter.WriteTo(Stream stream)
   at Microsoft.DiaSymReader.Tools.PdbConverter.ConvertPortableToWindows(PEReader peReader, MetadataReader pdbReader, Stream targetPdbStream, PdbConversionOptions options)
   at Microsoft.DiaSymReader.Tools.PdbConverter.ConvertPortableToWindows(PEReader peReader, Stream sourcePdbStream, Stream targetPdbStream, PdbConversionOptions options)
   at Microsoft.DotNet.Build.Tasks.ConvertPdbsToPortablePdbs.Execute()
```

I set the workaround to only retry once, which seems to work most of the time. It failed again during the retry at least once, though: https://github.com/dotnet/core-eng/issues/1782. However, it hasn't failed on retry again since then, so this isn't currently considered a hot issue as far as engineering services goes.

I was not able to repro except in the exact circumstances of the build machines hitting the issue, and even then, it only seemed to repro on the first attempt on the machine in a while. @vancem offered some tips to help try to repro consistently:

> Turning on the environment variable COMPLUS_GCStress=3 and running a non-trivial symbol conversion scenario for a long time (e.g. over a weekend), is likely to cause the bug to reproduce.     You would not want to just do Pdb2Pdb since that closes down the process (and hides corruption),   But you could have just directory full of portable PDBS that you write a little harness that simply converts them over and over in one process.   Set that up with Windbg to stop on an AV, and you probably will get a repo.   
> 
> A variation on GCStress=3 (which is considerably cheaper) is to use these managed debugging assistants that cause GCs every time you transition from manage to unmanaged or back.   
> 
> https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/gcmanagedtounmanaged-mda
> https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/gcunmanagedtomanaged-mda

It is quite possible that the bug we're hitting has already been fixed in the converter lib. [BuildTools uses](https://github.com/dotnet/buildtools/blob/583046217f68333c04521e119e9cf97eca6f2494/dependencies.props#L17) `Microsoft.DiaSymReader.Converter` `1.0.0-beta1-61722-03`, from 2017-05-22. If this isn't the case, we can file what we're hitting at https://github.com/dotnet/symreader-converter/issues.

/cc @vancem @tmat @crummel

**Comment by vancem** [comment]
I have hacked up my copy of Pdb2Pdb to do a whole directory in the same process repeatedly, and when I run it (even on only one thread and no stress mode), and it fails AVs very quickly (minutes).   From what I can tell right now it is native heap corruption.  

I will turn on some heap diagnostic tools to see about debugging it, but it looks like we have real bugs that still exist and we can attack.

**Comment by vancem** [comment]
If I turn on gflags page heap and run it COMPLUS_GCStress=3, the failure occurs with the first PDB (in theory I don't need my hacked up Pdb2Pdb).   It seems that there is some sort of double-releasing going on.  I am continuing to investigate.

**Comment by tmat** [comment]
@vancem Does it repro with the latest Pdb2Pdb build? (https://dotnet.myget.org/F/symreader-converter/api/v2/package/Pdb2Pdb/1.1.0-beta1-62221-01)

**Comment by vancem** [comment]
One possibility is is that the SymUnmanagedWriter COM interface is not MTA safe, and Pdb2Pdb's main method is not marked with the STAThread attribute.  Adding this attribute fixes the Pdb2Pdb crash in the simplest of cases.    From what I can tell MSBuild runs things in STAs by default (but there is an attribute to force it).  This may be part of the solution.  

However my test crashes in slightly more complex scenarios even with the STAThread attribute set.   The failure occurs EXACTLY when the finalizer is freeing memory (and with Gflags page alloc is unmapping the memory used by the object), and when the main thread is accessing this object.  Thus we definately have a double-free (or aliasing), issue.   Continuing to investigate...

**Comment by vancem** [comment]
@tmat - I built the Pdb2Pdb from source, but it is the latest source.    It uses the 10/16 version of microsoft.diasymreader.dll which is pretty current.    The bug reproduces here has not been fixed (and if you use GCStress + PageHeap repros very easily).

**Comment by tmat** [comment]
@vancem Interesting. I have not seen any crashes recently and we are now running the conversions in Roslyn tests every day. The SymReader interfaces are not MTA safe. I guess xUnit runs tests in STA. I should certainly add the STA attribute on the Main. Let me know when you find out more.

**Comment by tmat** [comment]
@vancem Actually, now I'm not that certain about my statement about MTA safety. Turns out our unit tests run in MTA and we have not seen any issues, but I'm not expert on COM, so there might be some lurking issue. In Roslyn we take care of accessing the SymReader COM objects in the same apartment they were created in, or marshalling it across if needed.

**Comment by vancem** [comment]
It is pretty clear to me that .NET Thinks the classes in Microsoft.DiaSymReader are MTA (for example the finalizer calls Release() directly on the finalizer thread), and I don't KNOW of any places where the symbol writer is obviously not MTA safe (The biggest no-nos are using shared thread-local storage or using global variables without synchronization), I am downgrading the STA hypothesis right now. 

What I have learned is that what seems to be going on is a premature free of a SymDocumentWriter by the finalizer.   However that particular Release() is correct (a reference is going away, it is just that the refcount is wrong so goes to zero too early.    This obviously causes corruption as later uses of the freed memory corrupt things.   I have to carefully inspect each AddRef and Release of this COM object to understand where we either missed an Addref or had too many Releases.   

Note that this is why the combination of page heap and GCStress is so effective in making things repro.   The GCStress insures there are lots of GCs with insure that the managed COM references are cleaned up aggressively (we do this as part of finalization) and the page heap makes it so that access to freed memory aggressively cause AVs.

**Comment by vancem** [comment]
I have found a fix.  Basically references to SymDocumentWriter were not being ref-counted properly.  This may be a bug in the native COM object, but as it turns out a wrapper needed to keep refernences to these SymDocumentWriters ANYWAY, and if we keep these references alive just a bit longer, we avoid the problem.

Without this change if I run with gflags page heap and GCStress=3 I conversions will crash on the very first PDB.  However with this change I have been running inprocess, parallel  conversions for many minutes (with these options) without failure.  

Note that there does seem to be memory leak associated with this code, but it is modest and an indepdendent problem.

**Comment by dagood** [comment]
Thanks, Vance!

@tmat, can you ping this thread when there's a new Microsoft.DiaSymReader.Converter package ready so BuildTools can upgrade? Looks like the build def is manually triggered.

**Comment by tmat** [comment]
New build is available now: https://dotnet.myget.org/F/symreader-converter/api/v2/package/Pdb2Pdb/1.1.0-beta1-62225-01

**Comment by tmat** [comment]
and https://dotnet.myget.org/F/symreader-converter/api/v2/package/Microsoft.DiaSymReader.Converter/1.1.0-beta1-62225-01

**Comment by vancem** [comment]
I have a update for build-tools prepared here https://github.com/dotnet/buildtools/pull/1758/files

**Comment by danmosemsft** [comment]
@dagood this can be closed right?

**Comment by dagood** [comment]
Yep, thanks for the reminder.
