### ISSUE TITLE
Handle hitting MAX_PATH in Microsoft.DotNet.Build.CloudTestTasks.DownloadFromAzure 

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1757]
We need to augment the Microsoft.DotNet.Build.CloudTestTasks.DownloadFromAzure class to check for MAX_PATH and log any file names that hit MAX_PATH, and either 

1) use MAX_PATH aware paths and APIs to make this just work or
2) Error out with a full list of all >= MAX_PATH files that it would have liked to have written to disk.

**Comment by Chrisboh** [comment]
@MattGal and @dagood  I have asked @riarenas to take a look into this one as #1646 was completed by Karthik.  I have asked him to reach out to you guys for questions and context.

**Comment by riarenas** [comment]
I've started taking a look at MAX_PATH and I have a few questions that would help me out deciding on the way to go for this issue:

1. Which OS do the machines that these blobs get downloaded run on? I see that the buildtools repo is built for Windows and Ubuntu. Are these the two platforms that need to be taken into account? I have found some possibility of getting long file paths to "just work" for Windows, but none for Ubuntu, which would mean erroring out with the list of files that violate going over path_max is the way to go there.

2.  How much access do we have to the machines that download the blobs? At least for [Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#maxpath) there are two possible solutions that we could explore so that long file names just work:
It seems .Net already supports long file paths since version 4.6.2 https://github.com/dotnet/corefx/issues/645. 
If that's not enough : 
-    Starting with Windows version 1607, the MAX_PATH restriction can be circumvented by setting a specific registry key. Setting this key lifts the MAX_PATH restriction from most Windows File and Directory APIs. 
-    Windows allows pre-pending the file path string with \\?\ to increase the MAX_PATH limitation to 32,767.

@MattGal @dagood any thoughts on these points? What would be the west way to test the current behavior for long file names?

**Comment by MattGal** [comment]
_Which OS do the machines that these blobs get downloaded run on?_ 

The .NET Core version of the task (i.e. the one that builds in the assembly which does not end in ".net45" must work on OSX, Linux, and Windows.  It needs to be platform agnostic.  Using the Azure SDK client libraries should already support this today, the reason it uses the Azure REST API currently was because of the time frame when it was written, i.e. .NET Core versions of Azure SDK client libs weren't anywhere near ready yet.  Do note, that MAX_PATH is a Windows-only problem.  

Yes, this can be tricky!  Your options here are either to solve the problem in such a way that it fits within the surface area of the cross-platform .NET Core, OR provide helper functionality that is different when the project is built for .NET 4.5+ desktop (feasible but might face some resistance from folks who want to see the code be identical)

_How much access do we have to the machines that download the blobs_

Build tasks on our build agents are generally running as admin accounts with full privileges.

_It seems .Net already supports long file paths since version 4.6.2 dotnet/corefx#645._

This is the solution where different functionality lights up when using the .NET45 (it's really 4.6.X) version of the DLL as mentioned above.  

_Starting with Windows version 1607, the MAX_PATH restriction can be circumvented by setting a specific registry key. Setting this key lifts the MAX_PATH restriction from most Windows File and Directory APIs._

That's an option, but I'm not sure when and if our build agents will go to that version (many are still running 2012 R2).  Ping @ilyas1974  for details there.

_Windows allows pre-pending the file path string with \?\_

Pretty sure this has been tried and hit some snags.  Not sure which.  Feel free to explore it!

Also, from literally dozens of lunch conversations about the subject, Mr. @JeremyKuhne might have some suggestions for you.

**Comment by JeremyKuhne** [comment]
I added support for `\\?\` to 4.6.2. Having a solution lower than that you'll need to P/Invoke directly to Windows APIs, which should be kept off the table, imho.

If 4.6.2 is your minbar, you could massage all paths on Windows with the `\\?\` prefix and it will work on both Core and Desktop. (Note that I haven't looked into Mono's behavior here.)  Logic is a little tricky, the code we use is [here](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/IO/PathInternal.Windows.cs). As paths must be fully normalized with `\\?\`, you must call `Path.GetFullPath()` **first**.

One advantage of using `\\?\` is that it will make things slightly faster as any subsequent usage in that format will skip both .NET and Windows normalization.

**Comment by riarenas** [comment]
MAX_PATH is windows only, but osx and linux  have similar (albeit more permissive) limits that depend on the file system in use. Is the goal to do something only in the Windows case since it's by far the most restrictive?

**Comment by MattGal** [comment]
@JeremyKuhne was there any solution that can be used in core?   I think it'd be ideal to not have special code for the desktop version of the task but it's not a big deal if so (as noted I think the main problem will be people talking about different code between desktop and core).

@riarenas I don't think we'll ever care about the max path lengths on Linux as those are well into the 1000s, and most of the time our build processes hit MAX_PATH the path is < 300 chars.

**Comment by JeremyKuhne** [comment]
> was there any solution that can be used in core?

`\\?\` will work on core and desktop when running on Windows. You'll still need to have Windows builds or do a runtime check to see if we're on Windows, of course.

**Comment by riarenas** [comment]
Thanks @JeremyKuhne for the tips.

So I think the way to go in this case is to use ```\\?\``` for WIndows only, taking into account the gotchas mentioned by Jeremy, and not worry about the path_max limitations on other platforms.

@MattGal Two followup questions: 
1. Are there any examples on how "per platform" code is usually handled? Wouldn't want to make a runtime check for Windows if that's not how it's usually addressed.
2. Any pointers on how I could test the changes?

**Comment by MattGal** [comment]
> 1. Are there any examples on how "per platform" code is usually handled? Wouldn't want to make a runtime check for Windows if that's not how it's usually addressed.

For a .NET Core class I'd use RuntimeInformation.IsOSPlatform, to figure out if I'm on Windows, then try parsing RuntimeInformation.OSDescription in case this doesn't work on older windows SKUs (that is, some folks might be using as old as Windows 7, we'd want to make sure the prefix worked there)

> 2. Any pointers on how I could test the changes?

I'd like to see **_your_** list of test cases, but as a minimum bar, I would:

- Exercise the DownloadFromAzure build task to download the contents of a container on at least one *nix system (your changes shouldn't affect this code path at all, but we'd rather not find out after merging the change)
- Create a container with  > max path named blobs, and download this to a local windows machine
- Download contents of any container into a path that is already near max path on the local windows machine.
- Try scenario at least once on Windows 7.

**Comment by riarenas** [comment]
> I'd like to see your list of test cases

Oh absolutely, and I should've worded this better. I'm not familiar with this codebase at all, so I was more wondering how build tasks are usually tested. Is it done by creating a custom project and adding the task while pointing to my privately built Microsoft.DotNet.Build.CloudTestTasks.dll?

**Comment by MattGal** [comment]
Here's how I test build tasks, attempted to be generalized:

```
<Project ToolsVersion="12.0" DefaultTargets="DebugThisTaskImWriting" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!-- 1. use your task --> 
  <UsingTask TaskName="TheNameOfSomeTask" AssemblyFile="<Path to assembly containing that task>"/>


  <!-- 1. Set up any properties or items it needs --> 
  <PropertyGroup>
     <Foo>Bar</Foo>
  </PropertyGroup>
  
  <ItemGroup>
    <Baz Include="Bop" >
  </ItemGroup>

  <Target Name="DebugThisTaskImWriting">
    <Message Importance="High" Text="Logging useful stuff about properties: Foo variable = $(Foo), etc." />

    <TheNameOfSomeTask
      Input1="Value"
      Input2="Value"
      ...>
      <Output TaskParameter="OutputParameter1FromTaskIfapplicable" PropertyName="Pizza" />
      <Output TaskParameter="OutputParameter2FromTaskIfapplicable" PropertyName="FrenchFries" />
    </TheNameOfSomeTask>

    <Message Importance="High" Text="I called that task and Output 1 contained @(Pizza) and Output 2 had @(FrenchFries)" />

  </Target>

</Project>
```

Depending on task complexity I will then call Debugger.Launch() early in the task (if i need a debugger) or just try to make my problems solvable using the MSBuild logging APIs.

**Comment by riarenas** [comment]
After some more digging around and testing in different platforms, this is what I found.

I misunderstood Jeremy. I thought support for ```\\?\``` would be possible in versions < 4.6.2. However, all the System.IO APIs in those versions make their own check for MAX_PATH, hence it becomes impossible to use them with long file paths as they Throw PathTooLongException. In versions >= 4.6.2 it's possible to configure everything so that those exceptions are not thrown, and that's the version that introduces the possibility of using ```\\?\``` 

With that caveat, I verified that adding the prefix works for both Core and Desktop. (Even in Win7)

This leaves me with two possible solutions: 
1. Bypassing the System.IO APIs and calling directly into the Windows APIs using ```\\?\```via P/Invoke.
Although this works and wasn't too hard to try out for the happy path, it's fragile, and seems like a dangerous rabbit hole for edge cases. 
2. Build a special version of the CloudTestTasks assembly that only targets 4.6, to take advantage of the enhanced functionality. 

For now I have added logging to the task for when the path is too long, and made it so the task returns a list of the paths that would've exceeded that limit in this pull request.
https://github.com/dotnet/buildtools/pull/1815

Is the MAX_PATH limit being hit often enough to warrant either of the alternatives?

**Comment by ViktorHofer** [comment]
// Auto-generated message

Going forward, the .NET team is using https://github.com/dotnet/arcade to develop the code and issues formerly in this repository. Feel free to reopen/move this issue if it still applies to servicing branches in this repository, or source code which now resides in the Arcade repository.
