### ISSUE TITLE
VS debugging experience broken

### ISSUE THREAD

**Issue by nguerrera** [dotnet/buildtools#181]
CopyTestToTestDirectory now only happens when the RunTestsForProject target is invoked. This broke the VS flow where build got everything ready and F5 could debug. Now I can only debug in VS if I run the tests on the command line first to copy the right files.

**Comment by eatdrinksleepcode** [comment]
Yes, CopyTestToTestDirectory was changed to only happen when RunTestsForProject is invoked. This was to speed up incremental command line builds.

Not being able to re-use our MSBuild tasks for running tests in Visual Studio is unfortunately very limiting. It seems we have four options:

1) Optimize for the command line, only copy files when they are needed for the targets that have been invoked by the current run. As this bug states, this breaks running and debugging tests in Visual Studio, and is therefore probably a non-starter.

2) Optimize for Visual Studio: always copy all relevant files to the test directory after build, whether or not tests will be run by the current invocation. This fixes running and debugging tests in Visual Studio, but also potentially results in a lot of unnecessary disk activity for command line builds. Not ideal, but probably viable.

3) Since Visual Studio essentially treats "Build" as a reserved target, we could stop using it on the command line. Instead, we could define a "Make" target (for example) that is the default for command line builds, and "Build" could combine "Make" and "CopyTestToTestDirectory" to enable Visual Studio scenarios. This is probably my preferred option, except that we don't actually define the "Build" target; it is defined in the built-in C# targets files. This makes it very difficult to redefine.

4) We could use the BuildingInVisualStudio property to alter the behavior: only invoke CopyTestToTestDirectory after Build when building in Visual Studio, and only invoke it before RunTestsForProject when not building in Visual Studio. Although this seems to give us everything we want, it is my least favorite option. I believe trying to differentiate the build behavior based on whether it is being invoked from a particular IDE was only mildly feasible when VS was the only IDE in widespread use for .NET projects. MonoDevelop (Xamarin Studio) already has to set this property in order to maintain compatibility with VS, which is unfortunate. But at least it is very similar to VS, so it's not completely irrational. But with .NET becoming open source and cross-platform, other IDEs are going to become more common. Should OmniSharp also set BuildingInVisualStudio to true? I think we need to find another way.

**Comment by nguerrera** [comment]
I have a version of #2 pending that in combination with smarter incremental copy and hard-linking is pretty darn fast. PR to follow...
