### ISSUE TITLE
Use x64 runtime for tests 

### ISSUE THREAD

**Issue by ellismg** [dotnet/buildtools#221]
Today project.lock.json and some of our targets force a 32 bit runtime when running tests.  I think we should move this to x64.  This aligns with what we are doing cross platform and will make it easies to produce runtime packages from github (where we don't have an x64 version of the runtime).

Are there any concerns about adopting a x64 bit runtime?

/cc @mellinoe @weshaggard @ericstj @stephentoub

**Comment by weshaggard** [comment]
I suspect we could go either direction as we need to also have support for x86 coreclr in the builds on github. 

However I don't have any particular concerns with supporting this as I think we need to eventually support both. It is just a matter of figuring out what all needs to happen to build out that support.

**Comment by mellinoe** [comment]
I think it probably makes more sense to just zip all of the stuff into an actual NuGet package and just download that for our tests, rather than have a checked-in json file that we restore. We could then just have an "x86" version, an "x64" version, an "ARM" version, etc. for our different test configurations. Then we would copy stuff over top of it like we do now and run it as usual. That would also let us version the test runtime independently from the rest of buildtools, which I think is desirable for some situations.

**Comment by ellismg** [comment]
@mellinoe I think I agree with your high level goals.  The place I would like to land is that the runtime we test on is independent of build tools and the nuget package for it is a nuget package we can build out of dotnet/coreclr.  We can't do the second thing yet today, but we should design a system such that once we are able to produce the runtime package for third parties it's the same package we use for our local tests.
