### ISSUE TITLE
AssemblyInfo.cs path clash

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#231]
https://github.com/dotnet/buildtools/pull/226 moved AssemblyInfo.cs to a path that can be common if projects have the same name.  I hit this in the reference assembly projects and worked around it.  I think the right fix here is to split out just the attributes needed by https://github.com/dotnet/buildtools/pull/217 and make those in a stable path that is shown in solution explorer.  Ideally you can just ship a static file in build tools so you don't have to worry about building before it shows up.  I didn't do this myself since I'm not familar with the tool you mention in the PR.  Can you please have a look and clean this up?  When you do feel free to delete my workaround.

**Comment by naamunds** [comment]
Fixed by https://github.com/dotnet/buildtools/commit/5b053072daed9abc674508acbe72f0bf5e069034 and https://github.com/dotnet/buildtools/commit/d4509423b630bacd446237241dadfe60710af9ec and https://github.com/dotnet/corefx/commit/1b8334fc397eef0ab0d811caff22f2eb731bfdbd.

I've verified the fix by successfully building "corefx\src\Microsoft.CSharp\ref\Microsoft.CSharp.csproj" and by verifying that the Multilingual App Toolkit functionality still works for the non-reference assemblies.
