### ISSUE TITLE
Best method to compile the output CS file generated by GenAPI

### ISSUE THREAD

**Issue by ratishphilip** [dotnet/buildtools#387]
What is the best method to compile the .CS file which is generated by the **Microsoft.DotNet.BuildTools.GenAPI** package?
I need to place the generated DLL in the **Ref** folder of the my NuGet package.

**Comment by weshaggard** [comment]
In corefx repo we generate it manually on demand and commit it to source control as opposed to generating it as part of the build.

**Comment by ratishphilip** [comment]
Wouldn't it be great if the script to build it manually could be generated along with the CS file?

**Comment by weshaggard** [comment]
There is an example build target that calls it https://github.com/dotnet/buildtools/blob/master/src/GenAPI.Desktop/Microsoft.DotNet.BuildTools.GenAPI.targets, not sure if that is along the lines of what you are looking for or not.

>Wouldn't it be great if the script to build it manually could be generated along with the CS file?

I assume by script you mean the csproj? There are just too many build systems to be able to generate a script that would work generically.

Also as for generating it automatically as part of the build we intentionally don't do that because it doesn't change much and don't want to pay the cost of generating every build. We also have numerous cases where the reference assembly doesn't have the exact same APIs that our libraries have a we have different implementations on different platforms.

**Comment by ratishphilip** [comment]
I meant a command line script using csc.exe which when executed would build the .cs file(s). This script would include all the required references.

**Comment by weshaggard** [comment]
Even to have a command line script it would need to know where to find the reference assemblies to pass for the references, as those will be different depending on your build environment. If you were to write a post target for the actual build of the library you are running GenAPI on you could potentially reuse those references but GenAPI itself has no idea where to find those reference assemblies to be able to generate a script that would build.
