### ISSUE TITLE
init-tools is not deleting the Tools directory when a new version of the runtime should get installed.

### ISSUE THREAD

**Issue by joperezr** [dotnet/buildtools#474]
When the BuildTools dependencies are updated, the init-tools script should delete all the contents of the tool runtime folder and then run the restore, instead of trying to restore it to the folder where the old runtime is located.

cc: @weshaggard

**Comment by ellismg** [comment]
Could we consider having everything restored to /Tools be prefixed with a tool runtime version?  This would help remove the need for restoring when I move between branches that have different runtime versions.

**Comment by joperezr** [comment]
That is actually a good idea, @weshaggard what do you think?  The only problem I see is that you might eventually end up having a Tools folder with 10+ different versions of the buildtools which most likely you won't be using all of them. Plus it doesn't really take that long to generate the tools, but it might be something to think about.

**Comment by weshaggard** [comment]
@ellismg I would like to avoid that because it adds other complications such as now needing to know the build tools version in all our msbuild targets files. That requires duplication and prevents us from actually importing common props/targets files from the tool-runtime which I really want because I want to move out a lot of the boiler-plate.
