### ISSUE TITLE
Support incremental test runs

### ISSUE THREAD

**Issue by ellismg** [dotnet/buildtools#60]
(from @eatdrinksleepcode in dotnet/corefx#678)

Executing a build twice in a row should ideally be as close to a no-op as possible. In CoreFX, unit tests are always executed during the second run, even when the both the main and test project have not changed. This could be fixed by specifying the correct Inputs and Outputs to the RunTests task. I would be happy to submit a PR with this change to the BuildTools project.

**Comment by eatdrinksleepcode** [comment]
(In reponse to @weshaggard at https://github.com/dotnet/corefx/issues/678#issuecomment-73352719)

My strong preference would be to (a) only run the tests if the test assembly has changed (i.e. something in the tests or their dependencies has changed), and (b) only copy files to the test directory if the tests need to be run. Unfortunately the way the test targets are structured today makes (b) difficult to achieve (because the copying of the test files is almost entirely disconnected from the running of the tests); I plan to look into alternative ways of executing the tests to alleviate this problem.

**Comment by weshaggard** [comment]
Thanks @eatdrinksleepcode I'm slowing working on changing how we restore packages as part of the build so I will think about this as well. If you want a early look at my changes see my branch https://github.com/weshaggard/corefx/tree/RestorePackagesPerProject.

**Comment by eatdrinksleepcode** [comment]
I started looking into this, and quickly discovered that the current xunit.console runner does not produce any output files, because the two output types built into xunit both require xsl transformation, which is not exposed in a portable contract. My idea is to add an option to the xunit.console runner to produce an output file with the raw xml results. This would give us output files to use in the RunTestsForProject task.

**Comment by alexperovich** [comment]
@eatdrinksleepcode I'm working on a change to do just that. There was a raw xml format just it was excluded along with the formats that require xslt.

**Comment by eatdrinksleepcode** [comment]
@alexperovich great! I will hold off on any further work on this until your change comes through.

**Comment by alexperovich** [comment]
Fix in PR #62

**Comment by weshaggard** [comment]
Thanks @alexperovich. @eatdrinksleepcode while this will mean we get a results file I don't know that we want to make the running of the test incremental on the existents of the results file. I would prefer it is incremental only on a passing test run. I definitely want to be able to re-run tests that have failures for debugging, etc, and preferably that wouldn't require a complete rebuild of the projects to accomplish.

**Comment by eatdrinksleepcode** [comment]
I completely agree.

I find myself (as I often do) pining for [Gradle](http://gradle.org/), where every task has a default up-to-date check that includes both the inputs and outputs AND whether the last task run succeeded. Unfortunately MSBuild not only lacks that functionality, but also lacks the necessary extension points to implement it from the outside.

The only ways that I can think of working around this feel hacky, and probably not worth doing. I will do some more research tonight and try to come up with something better. If you have any other ideas, please share.

**Comment by alexperovich** [comment]
@eatdrinksleepcode I hesitate to suggest using a marker file, but you could touch the file when the test run passes and use it in in the Output attribute of the target

**Comment by weshaggard** [comment]
@alexperovich @eatdrinksleepcode I don't think the mark file is a bad idea, that is what I was planning to do before we had the results file. While it is kind of a hack I've began to except it as a way to handle these type of cases in MSBuild and where the inputs/outputs are too complex and unknown statically.

As an example look at RestorePackages target in my branch https://github.com/weshaggard/corefx/blob/RestorePackagesPerProject/src/dir.targets I'm using working on a change to use this method to block the package restore and test copying for each build.

**Comment by eatdrinksleepcode** [comment]
Yes, that will work. I had misread [the documentation for incremental builds](https://msdn.microsoft.com/en-us/library/ms171483.aspx) to mean that skipping a task based on timestamps would only work if there is a one-to-one mapping from the inputs to the outputs; but upon re-reading I realize that it is making a statistical observation, not a functional statement.

@weshaggard, are you actively working on this, or can I take a crack at it?

**Comment by weshaggard** [comment]
@eatdrinksleepcode please go ahead and take a crack at this. At this point I'm primarily looking at the packaging, which is going slowly as I've not had enough time to finish it yet.

**Comment by weshaggard** [comment]
@eatdrinksleepcode is this still something you are planning to look into? Its fine if you don't have the time I will pick it up on my backlog.

**Comment by eatdrinksleepcode** [comment]
I actually spent a fair amount of time on this. Having the tests only run when there was a change was difficult because the file copying was always happening no matter what. So I worked on making the file copying only happen when there was a relevant change, and here ran into the problem that for the date/time stamp checking to working correctly, the test inputs needed to be separated from the output marker file. So I tried to fiddle with the directory structure of the test files, and ran into the problem that the tests for CoreFX are not actually run using the targets in buildtools, they are run using a custom target in CoreFX; so the directory structure change needed to be coordinated across repos.

At that point I saw all of the work that was being done on the test targets in CoreFX, and then saw you mention that you were working on pushing some CoreFX targets back to test tools, so I decided to hold off for a while until things stabilized. If things have settled down for the time being, I can take another run at this.

**Comment by weshaggard** [comment]
Yes if you see my recent changes in CoreFX https://github.com/dotnet/corefx/pull/1117 it now uses the targets from the build tools. Please have a look if you have time, but don't feel like you need to I will get to it eventually if you cannot.
