### ISSUE TITLE
run.exe Add option to select different projects based on OS

### ISSUE THREAD

**Issue by TyOverby** [dotnet/buildtools#908]
Add option to select different projects based on OS

For roslyn, on windows, we `msbuild Roslyn.sln`, but on linux, we `msbuild CrossPlatform.sln`.

**Comment by TyOverby** [comment]
@jaredpar

**Comment by jaredpar** [comment]
CC @maririos,

Think there is a more general item here.  It seems the config file needs to be able to specify different actions for a given command (`build`, `sync`, etc ...) based on the current OS.  Example I would run `sync.cmd` on Windows but `sync.sh` on Linux.  

Note: appologies if this behavior already exists.  I'm trying to find documentation on it and so far can't find it.

**Comment by maririos** [comment]
What we've been encouraging is that running something on Windows should be pretty similar to running it on Unix. Of course sometimes it is inevitable, but we do our best.
Taking into account that, one way to avoid this is by having files with same names but different extensions according to the OS. For the particular case that @TyOverby points, I consider it better to have a wrapper `buildsomething.cmd/sh` file to those projects, so that the developers don't have the need to learn a specific project name per OS.

In case the wrappers are scripts, run.exe accepts the Setting `Project=buildsomething` for `toolname=terminal`. run.exe will do `buildsomething.cmd` for windows and `buildsomething.sh` for unix.

Will this fix the issue? or do we want other behavior?.

Note: The documentation on the `tool` section of the `config.json` file is not very clear. I have an issue to improve it.

**Comment by jaredpar** [comment]
@maririos 

> What we've been encouraging is that running something on Windows should be pretty similar to running it on Unix. Of course sometimes it is inevitable, but we do our best.

Agree it would be ideal.  Unfortunately we still don't have a true universal script format for Windows and non-Windows.  It's possible csi.exe or bash (assuming better Windows support) could be that solution one day.  But until then we're going to be left with `tool.cmd` and `tool.sh` pairs :frowning:  

> Will this fix the issue? or do we want other behavior?.

I think that should fix the issue.  So long as we can have a cmd on Windows and sh on Linux we should be good to go.

**Comment by jaredpar** [comment]
@maririos also do you have an example of using such a tool that we could look at?  Anywhere in CoreFx or CoreCLR for example?

**Comment by maririos** [comment]
Sure, I'm using it in [build-native](https://github.com/maririos/corefx/blob/f2f7d665ed776c2ccf53d9b9cd6a6b690b1d583f/config.json#L455)

**Comment by maririos** [comment]
I'll close the issue then. Thanks!
